"""add authorization_documents and external_html

Revision ID: 0997102c8102
Revises: b73c0008566a
Create Date: 2026-06-29 09:41:12.103372
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0997102c8102'
down_revision: Union[str, None] = 'b73c0008566a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
