"""add authorization_documents and external_html

Revision ID: b73c0008566a
Revises: f2g3h4i5j6k7
Create Date: 2026-06-29 09:01:03.245889
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b73c0008566a'
down_revision: Union[str, None] = 'f2g3h4i5j6k7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_lines', sa.Column('authorization_documents', sa.JSON(), nullable=True))
    op.drop_column('credit_lines', 'authorization_text')
    op.alter_column('news', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'public'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'public'::character varying"))
    op.add_column('credit_lines', sa.Column('authorization_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('credit_lines', 'authorization_documents')
    # ### end Alembic commands ###
